//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juegos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CabeceraPedido()
        {
            this.DetallePago = new HashSet<DetallePago>();
            this.DetallePedido = new HashSet<DetallePedido>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public string estado_pedido { get; set; }
        public string numero_pedido { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePago> DetallePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
    }
}
