//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juegos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_Pago { get; set; }
        public string numero_Ticket { get; set; }
        public string pais { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public string imagen_recibo { get; set; }
        public Nullable<int> id_Banco { get; set; }
        public Nullable<int> id_Pedido { get; set; }
        public string imagen { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual CabeceraPedido CabeceraPedido { get; set; }
    }
}
