//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juegos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<int> id_Juego { get; set; }
        public Nullable<int> id_Cabecera { get; set; }
    
        public virtual CabeceraPedido CabeceraPedido { get; set; }
        public virtual Juego Juego { get; set; }
    }
}
